#!/usr/bin/env ruby
# coding: utf-8

# process a set of gem files and save stats on tag failures to a YAML file

require "rubygems"
require "yaml"
require "gem_lint"

gem_dir  = ARGV.shift

if gem_dir.nil?
  $stderr.puts "USAGE: ./collect_stats gem_dir"
  exit 1
elsif !File.directory?(gem_dir)
  $stderr.puts "#{gem_dir} not found"
  exit 1
end

gem_stats    = {}
author_stats = {}
tag_stats    = {}
misc_stats   = {}
gem_files    = Dir.glob(gem_dir + "/**/*.gem")

gem_files.each do |filename|
  basename = File.basename(filename,".gem")
  runner = GemLint::Runner.new(filename)
  unless runner.tags.empty?
    gem_stats[basename] = runner.tags
    runner.tags.each do |tag|
      tag_stats[tag] ||= []
      tag_stats[tag] << basename
    end
    emails = runner.email || ["unknown"]
    emails.each do |email|
      author_stats[email] ||= {}
      author_stats[email][basename] ||= []
      author_stats[email][basename] << runner.tags
    end
  end
end

misc_stats["total_gems"] = gem_files.size

File.open("by_gem.yml", "w")     { |out| YAML.dump(gem_stats, out)    }
File.open("by_author.yml", "w")  { |out| YAML.dump(author_stats, out) }
File.open("by_tag.yml", "w")     { |out| YAML.dump(tag_stats, out)    }
File.open("misc_stats.yml", "w") { |out| YAML.dump(misc_stats, out)   }
