Gem::Specification.new do |s|
  s.name              = "lint_report"
  s.version           = "0.0.1"
  s.summary           = "Run gem_lint against the complete rubygems archive"
  s.description       = "collates the output generated by running gem_lint against the most recent version of every public gem."
  s.authors           = ["James Healy"]
  s.email             = ["james@yob.id.au"]
  s.homepage          = "http://github.com/yob/lint_report"
  s.has_rdoc          = true
  s.rdoc_options      << "--title" << "Lint Report" << "--line-numbers"
  s.files             = Dir.glob("lib/**/*") + Dir.glob("bin/**/*") + ["README"]
  s.required_rubygems_version = ">=1.3.2"
  s.executables       << "lint_report"

  s.add_dependency('gem_lint', '>=0.0.4')

  s.add_development_dependency("rake")
  s.add_development_dependency("roodi")
  s.add_development_dependency("rspec", "~>2.0")
end
