#!/usr/bin/env ruby
# coding: utf-8

# Load raw stats from YAML files and print some basic reports

require "rubygems"
require "yaml"
require "bigdecimal"

stats_dir  = ARGV.shift

if stats_dir.nil?
  $stderr.puts "USAGE: ./report_stats stats_dir"
  exit 1
elsif !File.directory?(stats_dir)
  $stderr.puts "#{stats_dir} not found"
  exit 1
end

by_gem_path     = File.join(stats_dir, "by_gem.yml")
by_author_path  = File.join(stats_dir, "by_author.yml")
by_tag_path     = File.join(stats_dir, "by_tag.yml")
misc_stats_path = File.join(stats_dir, "misc_stats.yml")

[by_gem_path, by_author_path, by_tag_path, misc_stats_path].each do |path|
  if !File.file?(path)
    $stderr.puts "#{path} not found"
    exit 1
  end
end

gem_stats    = YAML.load_file(by_gem_path)
author_stats = YAML.load_file(by_author_path)
tag_stats    = YAML.load_file(by_tag_path)
misc_stats   = YAML.load_file(misc_stats_path)

total_gems = misc_stats["total_gems"]

tag_stats.each do |tag, gems|
  percent = BigDecimal.new(gems.size.to_s) / total_gems * 100
  puts "#{tag}: #{gems.size}/#{total_gems} (#{percent.round(2).to_s("F")}%)"
end
